"use client";

import {
  AlertDialog,
  AlertDialogAction,
  AlertDialogContent,
  AlertDialogDescription,
  AlertDialogFooter,
  AlertDialogHeader,
  AlertDialogTitle,
} from "@/components/ui/alert-dialog";
import { AlertTriangle } from "lucide-react";

interface DisclaimerDialogProps {
  open: boolean;
  onAccept: () => void;
}

export function DisclaimerDialog({ open, onAccept }: DisclaimerDialogProps) {
  return (
    <AlertDialog open={open}>
      <AlertDialogContent>
        <AlertDialogHeader>
          <div className="flex justify-center mb-4">
            <div className="p-3 bg-destructive/10 rounded-full">
              <AlertTriangle className="h-10 w-10 text-destructive" />
            </div>
          </div>
          <AlertDialogTitle className="text-center text-2xl font-bold">
            Important Disclaimer
          </AlertDialogTitle>
          <AlertDialogDescription className="text-center !mt-2 text-base">
            The information provided by Arogya Anugraha is generated by an AI model
            and is for informational purposes only. It is not a substitute for
            professional medical advice, diagnosis, or treatment.
          </AlertDialogDescription>
        </AlertDialogHeader>
        <div className="text-sm text-muted-foreground p-4 bg-muted/50 rounded-lg my-4">
          <ul className="list-disc list-inside space-y-2">
            <li>
              This tool does not provide a medical diagnosis.
            </li>
            <li>
              Always consult a qualified healthcare provider with any questions
              you may have regarding a medical condition.
            </li>
            <li>
              Never disregard professional medical advice or delay in seeking it
              because of something you have read from this application.
            </li>
          </ul>
        </div>
        <AlertDialogFooter>
          <AlertDialogAction onClick={onAccept} className="w-full h-11 text-base font-semibold">
            I Understand & Accept
          </AlertDialogAction>
        </AlertDialogFooter>
      </AlertDialogContent>
    </AlertDialog>
  );
}
